// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TequipWiseServer.Data;

#nullable disable

namespace TequipWiseServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240705003003_addManagerEmail")]
    partial class addManagerEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "23201a6a-a047-40ed-9b32-4788c684e564",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "9a5e0f8a-0776-407a-baf5-6c710c623a40",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        },
                        new
                        {
                            Id = "bcc7a254-59b4-4db1-8e63-39e95ecd1355",
                            ConcurrencyStamp = "3",
                            Name = "Manager",
                            NormalizedName = "Manager"
                        },
                        new
                        {
                            Id = "d1707d9f-75fb-40e9-bebb-84b208e9f72f",
                            ConcurrencyStamp = "4",
                            Name = "It Approver",
                            NormalizedName = "It Approver"
                        },
                        new
                        {
                            Id = "866407e9-e332-4b1f-9ec9-104596596897",
                            ConcurrencyStamp = "5",
                            Name = "Controller",
                            NormalizedName = "Controller"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailManger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DeptId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.Property<int>("EquipementSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipementSN"));

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierrid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EquipementSN");

                    b.HasIndex("supplierrid");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationDepartment", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocationId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("LocationDepartments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationPlant", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "PlantId");

                    b.HasIndex("PlantId");

                    b.ToTable("LocationPlants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.Property<int>("PlantNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantNumber"));

                    b.Property<string>("ApproverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ITApproverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SapNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plant_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantNumber");

                    b.HasIndex("ApproverId");

                    b.HasIndex("ITApproverId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Supplier", b =>
                {
                    b.Property<string>("SuplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suuplier_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TequipWiseServer.Models.UserEquipmentRequest", b =>
                {
                    b.Property<int>("UserEquipmentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserEquipmentRequestId"));

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departmang_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DepartmangconfirmStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DepartmangconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Finance_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinanceconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinanceconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ITconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ITconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberEquipment")
                        .HasColumnType("int");

                    b.Property<string>("PONum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PR_Not_ConfirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PR_Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequestStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierOffer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("controllerid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deptManagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("isNewhire")
                        .HasColumnType("bit");

                    b.Property<string>("itId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("order")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserEquipmentRequestId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("controllerid");

                    b.HasIndex("deptManagId");

                    b.HasIndex("itId");

                    b.ToTable("UserEquipmentRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool?>("ApproverActive")
                        .HasColumnType("bit");

                    b.Property<string>("BackupaproverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DepartmentDeptId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("StatusBackupProvider")
                        .HasColumnType("bit");

                    b.Property<string>("TeNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("backupActive")
                        .HasColumnType("bit");

                    b.Property<int?>("locaId")
                        .HasColumnType("int");

                    b.Property<int?>("plantId")
                        .HasColumnType("int");

                    b.HasIndex("BackupaproverId");

                    b.HasIndex("DepartmentDeptId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("locaId");

                    b.HasIndex("plantId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Supplier", "supplier")
                        .WithMany("Equipements")
                        .HasForeignKey("supplierrid");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationDepartment", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Department", "Department")
                        .WithMany("LocationDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany("LocationDepartments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationPlant", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany("LocationPlants")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.Plant", "Plant")
                        .WithMany("LocationPlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "ItApprover")
                        .WithMany()
                        .HasForeignKey("ITApproverId");

                    b.Navigation("Approver");

                    b.Navigation("ItApprover");
                });

            modelBuilder.Entity("TequipWiseServer.Models.UserEquipmentRequest", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Equipment", "Equipment")
                        .WithMany("UserEquipmentRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "User")
                        .WithMany("UserEquipmentRequests")
                        .HasForeignKey("UserId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Controller")
                        .WithMany("ControllerRequestToApprove")
                        .HasForeignKey("controllerid");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "DeparManag")
                        .WithMany("DeptMangRequestToApprove")
                        .HasForeignKey("deptManagId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "IT")
                        .WithMany("ItRequestToApprove")
                        .HasForeignKey("itId");

                    b.Navigation("Controller");

                    b.Navigation("DeparManag");

                    b.Navigation("Equipment");

                    b.Navigation("IT");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Backupaprover")
                        .WithMany()
                        .HasForeignKey("BackupaproverId");

                    b.HasOne("TequipWiseServer.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentDeptId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId");

                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("locaId");

                    b.HasOne("TequipWiseServer.Models.Plant", "Plant")
                        .WithMany("Users")
                        .HasForeignKey("plantId");

                    b.Navigation("Backupaprover");

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Manager");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.Navigation("LocationDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.Navigation("UserEquipmentRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Location", b =>
                {
                    b.Navigation("LocationDepartments");

                    b.Navigation("LocationPlants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.Navigation("LocationPlants");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Supplier", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.Navigation("ControllerRequestToApprove");

                    b.Navigation("DeptMangRequestToApprove");

                    b.Navigation("ItRequestToApprove");

                    b.Navigation("Subordinates");

                    b.Navigation("UserEquipmentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
