// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TequipWiseServer.Data;

#nullable disable

namespace TequipWiseServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240812094619_phonerequestmigration2")]
    partial class phonerequestmigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "4",
                            Name = "It Approver",
                            NormalizedName = "IT APPROVER"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "5",
                            Name = "Controller",
                            NormalizedName = "CONTROLLER"
                        },
                        new
                        {
                            Id = "6",
                            ConcurrencyStamp = "6",
                            Name = "ManagerBackupApprover",
                            NormalizedName = "MANAGERBACKUPAPPROVER"
                        },
                        new
                        {
                            Id = "7",
                            ConcurrencyStamp = "7",
                            Name = "ItBackupApprover",
                            NormalizedName = "ITBACKUPAPPROVER"
                        },
                        new
                        {
                            Id = "8",
                            ConcurrencyStamp = "8",
                            Name = "ControllerBackupApprover",
                            NormalizedName = "CONTROLLERBACKUPAPPROVER"
                        },
                        new
                        {
                            Id = "9",
                            ConcurrencyStamp = "9",
                            Name = "Approver",
                            NormalizedName = "APPROVER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailManger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("DeptId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.Property<int>("EquipementSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipementSN"));

                    b.Property<string>("EquipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierrid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EquipementSN");

                    b.HasIndex("supplierrid");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.EquipmentRequest", b =>
                {
                    b.Property<int>("EquipmentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentRequestId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewHireName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequestStatus")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierOffer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("TotalPrice")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("EquipmentRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationDepartment", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LocationId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("LocationDepartments");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationPlant", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "PlantId");

                    b.HasIndex("PlantId");

                    b.ToTable("LocationPlants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.PhoneRequest", b =>
                {
                    b.Property<int>("PhoneRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneRequestId"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AssetReceiveByEMployeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departmang_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DepartmangconfirmStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DepartmangconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCategorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForWho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HR_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HRconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HRconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ITconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ITconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewHireName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReceptionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacemnetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequestStatus")
                        .HasColumnType("bit");

                    b.Property<string>("TelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deptManagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("itId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("phoneRequestType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneRequestId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.HasIndex("ApplicationUserId2");

                    b.HasIndex("HRId");

                    b.HasIndex("UserId");

                    b.HasIndex("deptManagId");

                    b.HasIndex("itId");

                    b.ToTable("PhoneRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.Property<int>("PlantNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantNumber"));

                    b.Property<string>("ITApproverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("plant_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlantNumber");

                    b.HasIndex("ITApproverId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.SapNumber", b =>
                {
                    b.Property<int?>("SApID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SApID"));

                    b.Property<string>("Idcontroller")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SapNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SApID");

                    b.HasIndex("Idcontroller");

                    b.ToTable("SapNumbers");
                });

            modelBuilder.Entity("TequipWiseServer.Models.SubEquipmentRequest", b =>
                {
                    b.Property<int>("SubEquipmentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubEquipmentRequestId"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssetModele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssetReceiveByEMployeAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetSN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departmang_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DepartmangconfirmStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DepartmangconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Finance_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinanceconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FinanceconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IT_Not_confirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ITconfirmSatuts")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ITconfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PR_Not_ConfirmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PR_Status")
                        .HasColumnType("bit");

                    b.Property<float?>("PU")
                        .HasColumnType("real");

                    b.Property<int?>("QtEquipment")
                        .HasColumnType("int");

                    b.Property<bool?>("ReceptionStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SubRequestStatus")
                        .HasColumnType("bit");

                    b.Property<float>("Totale")
                        .HasColumnType("real");

                    b.Property<string>("controllerid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("deptManagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("itId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("order")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplierrid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SubEquipmentRequestId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ApplicationUserId1");

                    b.HasIndex("ApplicationUserId2");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("RequestId");

                    b.HasIndex("controllerid");

                    b.HasIndex("deptManagId");

                    b.HasIndex("itId");

                    b.HasIndex("supplierrid");

                    b.ToTable("subEquipmentRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Supplier", b =>
                {
                    b.Property<string>("SuplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suuplier_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool?>("ApproverActive")
                        .HasColumnType("bit");

                    b.Property<string>("BackupaproverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DepartmentDeptId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SapNumberId")
                        .HasColumnType("int");

                    b.Property<bool?>("StatusBackupProvider")
                        .HasColumnType("bit");

                    b.Property<string>("TeNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("backupActive")
                        .HasColumnType("bit");

                    b.Property<int?>("locaId")
                        .HasColumnType("int");

                    b.Property<int?>("plantId")
                        .HasColumnType("int");

                    b.HasIndex("BackupaproverId");

                    b.HasIndex("DepartmentDeptId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("SapNumberId");

                    b.HasIndex("locaId");

                    b.HasIndex("plantId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Supplier", "supplier")
                        .WithMany("Equipements")
                        .HasForeignKey("supplierrid");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("TequipWiseServer.Models.EquipmentRequest", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "User")
                        .WithMany("UserEquipmentRequests")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationDepartment", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Department", "Department")
                        .WithMany("LocationDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany("LocationDepartments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TequipWiseServer.Models.LocationPlant", b =>
                {
                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany("LocationPlants")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.Plant", "Plant")
                        .WithMany("LocationPlants")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("TequipWiseServer.Models.PhoneRequest", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("DeptMangPhoneRequestsToApprove")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("HRRequestsPhoneToApprove")
                        .HasForeignKey("ApplicationUserId1");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("ItRequestsPhoneToApprove")
                        .HasForeignKey("ApplicationUserId2");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "HR")
                        .WithMany()
                        .HasForeignKey("HRId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "User")
                        .WithMany("PhoneRequests")
                        .HasForeignKey("UserId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "DeparManag")
                        .WithMany()
                        .HasForeignKey("deptManagId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "IT")
                        .WithMany()
                        .HasForeignKey("itId");

                    b.Navigation("DeparManag");

                    b.Navigation("HR");

                    b.Navigation("IT");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "ItApprover")
                        .WithMany()
                        .HasForeignKey("ITApproverId");

                    b.Navigation("ItApprover");
                });

            modelBuilder.Entity("TequipWiseServer.Models.SapNumber", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Controller")
                        .WithMany()
                        .HasForeignKey("Idcontroller");

                    b.Navigation("Controller");
                });

            modelBuilder.Entity("TequipWiseServer.Models.SubEquipmentRequest", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("DeptMangRequestToApprove")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("ItRequestToApprove")
                        .HasForeignKey("ApplicationUserId1");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", null)
                        .WithMany("ControllerRequestToApprove")
                        .HasForeignKey("ApplicationUserId2");

                    b.HasOne("TequipWiseServer.Models.Equipment", "Equipment")
                        .WithMany("UserEquipmentRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TequipWiseServer.Models.EquipmentRequest", "EquipRequest")
                        .WithMany("EquipmentSubRequests")
                        .HasForeignKey("RequestId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Controller")
                        .WithMany()
                        .HasForeignKey("controllerid");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "DeparManag")
                        .WithMany()
                        .HasForeignKey("deptManagId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "IT")
                        .WithMany()
                        .HasForeignKey("itId");

                    b.HasOne("TequipWiseServer.Models.Supplier", "supplier")
                        .WithMany("subrequests")
                        .HasForeignKey("supplierrid");

                    b.Navigation("Controller");

                    b.Navigation("DeparManag");

                    b.Navigation("EquipRequest");

                    b.Navigation("Equipment");

                    b.Navigation("IT");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Backupaprover")
                        .WithMany()
                        .HasForeignKey("BackupaproverId");

                    b.HasOne("TequipWiseServer.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentDeptId");

                    b.HasOne("TequipWiseServer.Models.ApplicationUser", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId");

                    b.HasOne("TequipWiseServer.Models.SapNumber", "SapNumber")
                        .WithMany("Users")
                        .HasForeignKey("SapNumberId");

                    b.HasOne("TequipWiseServer.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("locaId");

                    b.HasOne("TequipWiseServer.Models.Plant", "Plant")
                        .WithMany("Users")
                        .HasForeignKey("plantId");

                    b.Navigation("Backupaprover");

                    b.Navigation("Department");

                    b.Navigation("Location");

                    b.Navigation("Manager");

                    b.Navigation("Plant");

                    b.Navigation("SapNumber");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Department", b =>
                {
                    b.Navigation("LocationDepartments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Equipment", b =>
                {
                    b.Navigation("UserEquipmentRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.EquipmentRequest", b =>
                {
                    b.Navigation("EquipmentSubRequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Location", b =>
                {
                    b.Navigation("LocationDepartments");

                    b.Navigation("LocationPlants");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Plant", b =>
                {
                    b.Navigation("LocationPlants");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TequipWiseServer.Models.SapNumber", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TequipWiseServer.Models.Supplier", b =>
                {
                    b.Navigation("Equipements");

                    b.Navigation("subrequests");
                });

            modelBuilder.Entity("TequipWiseServer.Models.ApplicationUser", b =>
                {
                    b.Navigation("ControllerRequestToApprove");

                    b.Navigation("DeptMangPhoneRequestsToApprove");

                    b.Navigation("DeptMangRequestToApprove");

                    b.Navigation("HRRequestsPhoneToApprove");

                    b.Navigation("ItRequestToApprove");

                    b.Navigation("ItRequestsPhoneToApprove");

                    b.Navigation("PhoneRequests");

                    b.Navigation("Subordinates");

                    b.Navigation("UserEquipmentRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
